<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\HandymanController;
use App\Http\Controllers\HomeownerController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Public home page
Route::get('/', function () {
    return view('welcome');
});

// Default Breeze dashboard (shared)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Authenticated user routes (from Breeze)
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

/*
|--------------------------------------------------------------------------
| Role-Based Dashboards
|--------------------------------------------------------------------------
|
| These routes are protected by both authentication and the custom
| "role" middleware registered in bootstrap/app.php.
|
*/

// Admin-only routes
Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/admin/dashboard', [AdminController::class, 'dashboard'])->name('admin.dashboard');
});

// Handyman-only routes
Route::middleware(['auth', 'role:handyman'])->group(function () {
    Route::get('/handyman/dashboard', [HandymanController::class, 'dashboard'])->name('handyman.dashboard');
});

// Homeowner-only routes
Route::middleware(['auth', 'role:homeowner'])->group(function () {
    Route::get('/homeowner/dashboard', [HomeownerController::class, 'dashboard'])->name('homeowner.dashboard');
});

// Auth routes generated by Breeze
require __DIR__.'/auth.php';


Route::middleware(['auth','role:admin'])->group(function() {
    Route::get('/admin/dashboard', [AdminController::class, 'dashboard'])->name('admin.dashboard');

    // GET /admin/users (index)​
    // GET /admin/users/{user}/edit (edit)​
    // PUT /admin/users/{user} (update)​
    // DELETE /admin/users/{user} (destroy)
    Route::resource('admin/users', AdminController::class)->except(['create','store','show']);

    //Veifying a handyman
    Route::post('/admin/users/(user)/verfiy',[AdminController::class,'verifyHandyman'])->name('/admin.users.verify');
    //un-verifying a handyman
    Route::post('/admin/users/(user)/unverify',[AdminController::class,'unverifyHandyman'])->name('admin.users.unverify');
});

Route::middleware('auth')->group(function(){
    Route::get('/profile', [ProfileController::class,'edit'])->name('profile.edit');

    Route::post('/bookings/{booking}/review',[ReviewController::class,'store'])->name('reviews.store');
});
