<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\HandymanController;
use App\Http\Controllers\HomeownerController;
use App\Http\Controllers\ReviewController;


// Public listing (or auth can be required)
Route::get('/handymen', [HandymanController::class, 'index'])->name('handymen.index');
Route::get('/handymen/{handyman}', [HandymanController::class, 'show'])->name('handymen.show');

// Handyman update profile (auth + handyman)
Route::post('/handyman/profile/update', [HandymanController::class, 'updateProfile'])
    ->middleware(['auth','role:handyman'])->name('handyman.profile.update');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Public home page
Route::get('/', function () {
    return Auth::check() ? view('dashboard') : redirect('/login');
});

// Default Breeze dashboard (shared)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Authenticated user routes (from Breeze)
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    //Homewoner, submit a review
    Route::post('/bookings/{booking}/review',[ReviewController::class,'store'])->name('reviews.store');
});

/*
|--------------------------------------------------------------------------
| Role-Based Dashboards
|--------------------------------------------------------------------------
|
| These routes are protected by both authentication and the custom
| "role" middleware registered in bootstrap/app.php.
|
*/

// Admin-only routes
Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/admin/dashboard', [AdminController::class, 'dashboard'])->name('admin.dashboard');

    // GET /admin/users (index)​
    // GET /admin/users/{user}/edit (edit)​
    // PUT /admin/users/{user} (update)​
    // DELETE /admin/users/{user} (destroy)
    Route::resource('admin/users', AdminController::class)->except(['create','store','show']);


    //Veifying a handyman
    Route::post('/admin/users/{user}/verify',[AdminController::class,'verifyHandyman'])->name('admin.users.verify');
    //un-verifying a handyman
    Route::post('/admin/users/{user}/unverify',[AdminController::class,'unverifyHandyman'])->name('admin.users.unverify');
});




// Handyman-only routes
Route::middleware(['auth', 'role:handyman'])->group(function () {
    Route::get('/handyman/dashboard', [HandymanController::class, 'dashboard'])->name('handyman.dashboard');
});

// Homeowner-only routes
Route::middleware(['auth', 'role:homeowner'])->group(function () {
    Route::get('/homeowner/dashboard', [HomeownerController::class, 'dashboard'])->name('homeowner.dashboard');
});

// Auth routes generated by Breeze
require __DIR__.'/auth.php';
